### PR TITLE
Rework logging and UI configuration

### PR DESCRIPTION
**Pull request by e2**
Related to https://github.com/guard/guard/pull/851

### CODE REVIEW

**Comment by christhekeele** [comment]
Running master, none of my lumberjack options seem honored now. I think it's because the [Logger::Config](https://github.com/guard/guard/pull/852/files#diff-097a4b622771b741d48f1bc71982d91eR6) class [instantiated within the UI Config when it gets created](https://github.com/guard/guard/pull/852/files#diff-2cd1247fc5f903f90b835bac5ff35b4eR31) never gets updated with user preferences. Perhaps `[]=` should be overwritten on UI Config too?

**Comment by e2** [comment]
> Running master, none of my lumberjack options seem honored now.

Can you give me an example of how you're setting those options?

The DSL logger setup should work:

https://github.com/guard/guard/wiki/Guardfile-DSL---Configuring-Guard#logger

**Comment by christhekeele** [comment]
My Guardfile contains, at root level:

```ruby
logger ({
  level: :debug,
  template: "[\e[48;5;238m\e[96m:progname\e[39m\e[1m-:severity\e[21m\e[2m@:time\e[22m\e[0m] => :message",
  time_format: "%I:%M%p",
})
```

Using pry, I can tell the [DSL receives this on line 352 correctly](https://github.com/guard/guard/blob/master/lib/guard/dsl.rb#L352) :

```ruby
options
#=> {:level=>:debug,
#=> :template=>"[\e[48;5;238m\e[96m:progname\e[39m\e[1m-:severity\e[21m\e[2m@:time\e[22m\e[0m] => :message",
#=> :time_format=>"%I:%M%p"}

UI.options
#=> {"only"=>nil, "except"=>nil, "device"=>nil}

UI.options.merge!(options)
#=> {"only"=>nil,
#=>  "except"=>nil,
#=>  "device"=>nil,
#=>  "level"=>:debug,
#=>  "template"=>"[\e[48;5;238m\e[96m:progname\e[39m\e[1m-:severity\e[21m\e[2m@:time\e[22m\e[0m] => :message",
#=>  "time_format"=>"%I:%M%p"}
```

The problem is reading these options. `UI.options.logger_config` is initialized on the creation of the `options` object, before it is `merge`d with the user options. The logger config object never again refers to its containing options object to read its keys to determine what it should be, and the options object doesn't override setters to pass the deprecated_logger_opts down to the logger config. Therefore the logger config always returns the defaults:

```ruby
UI.options
#=> {"only"=>nil,
#=>  "except"=>nil,
#=>  "device"=>nil,
#=>  "level"=>:debug,
#=>  "template"=>"[\e[48;5;238m\e[96m:progname\e[39m\e[1m-:severity\e[21m\e[2m@:time\e[22m\e[0m] => :message",
#=>  "time_format"=>"%I:%M%p"}

UI.options.logger_config
#=> {"progname"=>"Guard", "level"=>:info, "template"=>":time - :severity - :message", "time_format"=>"%H:%M:%S", "flush_seconds"=>0}
```

**Comment by e2** [comment]
Thanks.

I think attempting to set options after the logger is initialized
should raise an exception, unless those can be set directly on the
logger. I think every option should be separate.

Looks like the LumberJack logger needs a wrapper so that options can
be sanely set (or errors raise if not).

And the logger config would then be part of the logger wrapper.

**Comment by christhekeele** [comment]
I agree it shouldn't be mutable. I just know that `merge` uses `[]=` under the covers, so overriding that the same way [you've overridden `[]`](https://github.com/guard/guard/blob/master/lib/guard/ui/config.rb#L48-L57) would make the prescribed DSL usage work. Right now the verbatim instructions aren't working, I'm not trying to do anything fancy with post-configuration mutation.

I also see comments about deprecating those logger options, so if you had a different mechanism in mind it might be cleaner to implement it now, and have the `DSL.logger` method invoke it instead of option munging deeper in the `UI.options` logic.

**Comment by e2** [comment]
Good points!

Personally, I want to move away from using hashes. They hurt more than
they help. It's best to just use plain methods and really check the
options properly. Hashes seem flexible, but they're a nightmare when a
project matures.

I don't mind crashes actually - as a way of preventing mutation. If it
isn't handles, it's undefined. If it's undefined, it should crash so
that it can be quickly reproduced, patched and released.

I'd actually prefer to merge a PR for code that just throws a new
exception for something no one has time to fix.

Getting things working is a priority. Coverage is important, though
quality comes first.

There are a few things I have in mind/planned here:

  1. Moving away from hashes (or using encapsulation at least)

  2. Wrapping the logger so it can be easily reconfigured

  3. Moving Guard::UI into a different gem - just like notifications
  were extracted into the Notiffany project

  4. Moving away from the DSL (making it optional - there's a better
  DSL already planned)

  5. Getting rid of UI.options (It will probably become something like
  UI#connect(options) which will make things more reasonable and
  managable. The constant should be replaced with an instance.

Meanwhile, the DSL should be compatible, so the way you're setting
options has to work. It's a bug. I might take a shot at it this
Saturday.

The deprecation is so that the UI::Config option doesn't get logger
options. The logger (logger wrapper) should be getting those options.

Again, this shouldn't affect the DSL. I relied on merge only because
it's how the DSL already changes the config.

I agree that DSL.logger should be reworked. I just didn't have time to
rework that part of the codebase. The DSL already does some
validating.

My ideal approach to this would be:

  - have the Logger config throw exceptions for unsupported errors
  - have the DSL catch those errors and turn them into warnings (where
    appropriate)

The idea is that the DSL if for end users, but anything below should
by a Ruby API suitable for extracting into another gem.

The only major issue with the logger is: if you log errors, you have
to set things up so you don't get an error until the logger is
configured.

So for now I delayed the logger initialization. The DSL should be
responsible for configuring the logger. If there's no logger available
and there's an error, it should either raise or output with default
options.

If you have a suggestion for a patch, just open a PR. I'd rather even
merge an incomplete PR and refactor other parts of Guard in one
sitting - rather than for you (or anyone else) to rebase a patch
against a stack of changes.

**Comment by fwoelm** [comment]
Is there a solution or workaround for this?

Using Guard 2.14.1, I'm trying to set logging options in my Guardfile. I'm following the [instructions from the Guard wiki](https://github.com/guard/guard/wiki/Guardfile-DSL---Configuring-Guard#logger):

```
logger level:       :warn,
       template:    '[:severity - :time - :progname] :message',
       time_format: 'at %I:%M%p',
       device:      'guard.log'
```

Only the device parameter seems to be honored. The other ones are ignored :(

**Pull request merged**
