### PR TITLE
Replace Coveralls by Code Climate

### PR DESCRIPTION
**Pull request by rymai**
This would group the code quality and coverage in one place, plus, their badge has the right size! :D

### CODE REVIEW

**Comment by e2** [comment]
I don't mind the the sizes as much as the coverage-changes reports. The two main problems with Coveralls I see are:
- the strange "coverage changed by: %0.0000001" reports that I never can tell if coverage actually decreased or increased
- the lack of quickly seeing how the coverage changed (basically, I'd prefer a "diff of diffs" to show where coverage changed and how)

I don't use code climate, and ultimately I don't mind either way as long as coverage prevents me from major screwups.

**Comment by rymai** [comment]
Fair enough, thanks! Let's see if that's better than Coveralls!

**Comment by rymai** [comment]
FYI: https://codeclimate.com/github/guard/guard/code?sort=covered_percent&sort_direction=asc

**Comment by e2** [comment]
> FYI: https://codeclimate.com/github/guard/guard/code?sort=covered_percent&sort_direction=asc

LOL, I know. That was the FIRST(!!) thing I checked out as soon as the coverage was refreshed!

**Comment by rymai** [comment]
^^

**Pull request merged**
