### PR TITLE
Pry 0.12.0 Deprecation warnings

### PR DESCRIPTION
**Pull request by chadmetcalf**
Addresses deprecation in Pry 0.12.0

### CODE REVIEW

**Comment by rymai** [comment]
@chadmetcalf Thank you, looks good to me! :heart: :yellow_heart: :green_heart: :rocket:

**Comment by Aqualon** [comment]
Do you have plans for a release in the near future?

**Comment by rymai** [comment]
I will prepare a new version!

**Comment by rymai** [comment]
@chadmetcalf @Aqualon Guard 2.15.0 released! 🎉

**Pull request merged**
